# Generated by Django 6.0 on 2025-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], default='farmer', max_length=10),
        ),
    ]
